[project]
name = "palmeras-uy"
version = "0.1.0"
description = "App para registro del tratamiento de las Palmeras en Montevideo"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.3",
    "psycopg2>=2.9.10",
    "python-dotenv>=1.1.0",
    "tzdata>=2025.2",
]
