# Generated by Django 5.2.3 on 2025-06-20 19:03

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):
    operations = [CreateExtension("postgis")]
