# Generated by Django 5.2.3 on 2025-06-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('puntos', '0001_gis_extension'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palmera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32, unique=True, verbose_name='Código')),
                ('lon', models.FloatField(verbose_name='Longitud')),
                ('lat', models.FloatField(verbose_name='Latitud')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Palmera',
                'verbose_name_plural': 'Palmeras',
                'ordering': ['created_at'],
            },
        ),
    ]
