# Generated by Django 5.2.3 on 2025-06-20 20:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puntos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palmera',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='palmera',
            name='lon',
        ),
        migrations.AddField(
            model_name='palmera',
            name='coords',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Coordenadas'),
        ),
    ]
