# Generated by Django 5.2.3 on 2025-06-20 20:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puntos', '0003_remove_palmera_lat_remove_palmera_lon_palmera_coords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='palmera',
            name='coords',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='Coordenadas'),
        ),
    ]
